test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: forten_test
  pool: 5
  username: root
  host: 127.0.0.1
  port: 3306
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: forten
  pool: 5
  username: root
  host: 127.0.0.1
  port: 3306
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: forten
  pool: 5
  username: root
  password: meetmeety
  host: 127.0.0.1
  port: 3306
  timeout: 5000
